export enum Category {
    Anything= '',
    GeneralKnowledge = 9,
    Books,
    Film,
    Music,
    MusicalsAndTheatres,
    TV,
    VideoGames,
    BoardGames,
    ScienceNature,
    Computers,
    Mathematics,
    Mythology,
    Sports,
    Geography,
    History,
    Politics,
    Art,
    Celebrities,
    Animals,
    Vehicles,
    Comics,
    Gadgets,
    AnimeAndManga,
    CartoonAndAnimations
  }